# Generated by Django 5.0.6 on 2026-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatsDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                ("uv", models.IntegerField(default=0, verbose_name="独立访客数")),
                ("pv", models.IntegerField(default=0, verbose_name="页面浏览量")),
                (
                    "assessment_starts",
                    models.IntegerField(default=0, verbose_name="测评开始数"),
                ),
                (
                    "assessment_completes",
                    models.IntegerField(default=0, verbose_name="测评完成数"),
                ),
                (
                    "payment_clicks",
                    models.IntegerField(default=0, verbose_name="支付点击数"),
                ),
                (
                    "payment_successes",
                    models.IntegerField(default=0, verbose_name="支付成功数"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="收入"
                    ),
                ),
                (
                    "share_clicks",
                    models.IntegerField(default=0, verbose_name="分享点击数"),
                ),
                (
                    "referral_visits",
                    models.IntegerField(default=0, verbose_name="分享回流数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "日报统计",
                "verbose_name_plural": "日报统计",
                "db_table": "stats_daily",
            },
        ),
        migrations.CreateModel(
            name="CustomerServiceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=36,
                        null=True,
                        verbose_name="用户会话ID",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="联系方式"
                    ),
                ),
                ("message", models.TextField(verbose_name="问题描述")),
                (
                    "order_no",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="相关订单号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("replied", "已回复"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "reply",
                    models.TextField(blank=True, null=True, verbose_name="回复内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回复时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "客服留言",
                "verbose_name_plural": "客服留言",
                "db_table": "customer_service_message",
                "indexes": [
                    models.Index(fields=["uuid"], name="idx_cs_uuid"),
                    models.Index(fields=["status"], name="idx_cs_status"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True, max_length=36, verbose_name="用户会话ID"
                    ),
                ),
                (
                    "assessment_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="关联测评记录ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="相关订单号"
                    ),
                ),
                (
                    "mbti_type",
                    models.CharField(max_length=4, verbose_name="测评结果类型"),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("career_mismatch", "方向完全不对"),
                            ("career_partial", "部分匹配"),
                            ("report_rating", "报告评分"),
                            ("report_text", "报告文字反馈"),
                        ],
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "career_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="相关职业ID"
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[("up", "赞"), ("down", "踩")],
                        max_length=4,
                        null=True,
                        verbose_name="评分",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="反馈内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "db_table": "feedback",
                "indexes": [
                    models.Index(fields=["uuid"], name="idx_fb_uuid"),
                    models.Index(fields=["assessment_id"], name="idx_fb_assess"),
                    models.Index(fields=["career_id"], name="idx_fb_career"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True, max_length=36, verbose_name="用户会话ID"
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="事件名称"
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(blank=True, null=True, verbose_name="事件数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "埋点事件",
                "verbose_name_plural": "埋点事件",
                "db_table": "tracking_event",
                "indexes": [
                    models.Index(fields=["uuid"], name="idx_track_uuid"),
                    models.Index(fields=["event_name"], name="idx_track_event"),
                    models.Index(fields=["created_at"], name="idx_track_created"),
                ],
            },
        ),
    ]
