# Generated by Django 5.2 on 2026-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "career_name",
                    models.CharField(max_length=100, verbose_name="职业名称"),
                ),
                (
                    "career_category",
                    models.CharField(max_length=50, verbose_name="职业类别"),
                ),
                ("description", models.TextField(verbose_name="职业描述")),
                (
                    "matching_archetypes",
                    models.JSONField(default=list, verbose_name="匹配的画像 ID 列表"),
                ),
                (
                    "matching_riasec_codes",
                    models.JSONField(default=list, verbose_name="匹配的 RIASEC 码列表"),
                ),
                (
                    "salary_range",
                    models.CharField(max_length=50, null=True, verbose_name="薪资范围"),
                ),
                (
                    "growth_prospect",
                    models.CharField(max_length=20, null=True, verbose_name="发展前景"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "职业",
                "verbose_name_plural": "职业",
                "db_table": "career",
                "ordering": ["career_name"],
            },
        ),
    ]
