[mypy]
python_version = 3.11
strict = True
ignore_missing_imports = True
exclude = (migrations|settings|\.venv|staticfiles|deploy)

[mypy-*.models.*]
disable_error_code = type-arg

[mypy-*.settings.*]
disable_error_code = no-redef

[mypy-*.serializers.*]
disable_error_code = type-arg, assignment

[mypy-*.urls.*]
disable_error_code = valid-type, no-untyped-def

[mypy-*.admin_urls.*]
disable_error_code = valid-type, no-untyped-def

[mypy-*.admin_views.*]
disable_error_code = no-untyped-def, attr-defined, has-type, dict-item, assignment

[mypy-*.views.*]
disable_error_code = has-type, no-any-return, assignment

[mypy-payment.services.report_service.*]
disable_error_code = no-any-return, arg-type, assignment, attr-defined, type-arg, call-overload

[mypy-payment.services.wechat_pay.*]
disable_error_code = arg-type

[mypy-payment.services.alipay.*]
disable_error_code = arg-type

[mypy-payment.services.callback_handler.*]
disable_error_code = arg-type

[mypy-assessment.services.*]
disable_error_code = attr-defined, arg-type, type-arg, assignment

[mypy-assessment.scoring.*]
disable_error_code = type-arg, arg-type, call-overload, unused-ignore, attr-defined

[mypy-common.*]
disable_error_code = no-any-return, attr-defined

[mypy-stats.*]
disable_error_code = type-arg, attr-defined, dict-item, assignment, valid-type

[mypy-stats.tasks.*]
disable_error_code = attr-defined

[mypy-tests.*]
disable_error_code = type-arg, arg-type, attr-defined, unused-ignore, call-overload
