# Generated by Django 5.2 on 2026-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_token",
                    models.CharField(db_index=True, max_length=36, verbose_name="会话令牌"),
                ),
                (
                    "device_fingerprint",
                    models.CharField(db_index=True, max_length=64, verbose_name="设备指纹"),
                ),
                (
                    "answers",
                    models.TextField(
                        help_text="AES-256 加密的答题数据（JSON 格式）",
                        verbose_name="答题数据",
                    ),
                ),
                (
                    "archetype_id",
                    models.IntegerField(null=True, verbose_name="画像原型 ID"),
                ),
                (
                    "archetype_name",
                    models.CharField(max_length=50, null=True, verbose_name="画像名"),
                ),
                (
                    "riasec_code",
                    models.CharField(max_length=3, null=True, verbose_name="RIASEC 码"),
                ),
                ("o_score", models.FloatField(null=True, verbose_name="开放性百分位")),
                ("c_score", models.FloatField(null=True, verbose_name="尽责性百分位")),
                ("e_score", models.FloatField(null=True, verbose_name="外向性百分位")),
                ("a_score", models.FloatField(null=True, verbose_name="宜人性百分位")),
                ("n_score", models.FloatField(null=True, verbose_name="神经质百分位")),
                ("confidence", models.FloatField(null=True, verbose_name="置信度")),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="测评是否有效"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(null=True, verbose_name="答题耗时（秒）"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "测评记录",
                "verbose_name_plural": "测评记录",
                "db_table": "assessment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField(verbose_name="题目陈述")),
                (
                    "dimension_prefix",
                    models.CharField(
                        help_text="BO/BC/BE/BA/BN/RR/RI/RA/RS/RE/RC",
                        max_length=2,
                        verbose_name="维度前缀",
                    ),
                ),
                (
                    "is_reverse",
                    models.BooleanField(default=False, verbose_name="是否反向计分"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("ocean", "大五人格"),
                            ("riasec", "RIASEC"),
                            ("validity", "效度题"),
                        ],
                        max_length=10,
                        verbose_name="题目类型",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="题目顺序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "db_table": "question",
                "ordering": ["order"],
            },
        ),
    ]
