# Generated by Django 5.0.6 on 2026-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True, max_length=36, verbose_name="用户会话ID"
                    ),
                ),
                (
                    "browser_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="浏览器指纹",
                    ),
                ),
                (
                    "mbti_type_code",
                    models.CharField(max_length=4, verbose_name="测评结果类型"),
                ),
                ("dimension_scores", models.JSONField(verbose_name="维度得分")),
                ("facet_scores", models.JSONField(verbose_name="面向得分")),
                (
                    "consistency_flag",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("facet_inconsistent", "面向不一致"),
                            ("reverse_inconsistent", "反向题不一致"),
                            ("extreme_response", "极端作答"),
                            ("facet_and_extreme", "面向不一致且极端作答"),
                        ],
                        default="normal",
                        max_length=32,
                        verbose_name="一致性标记",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "测评记录",
                "verbose_name_plural": "测评记录",
                "db_table": "assessment",
                "indexes": [
                    models.Index(fields=["uuid"], name="idx_assess_uuid"),
                    models.Index(fields=["browser_fingerprint"], name="idx_assess_fp"),
                    models.Index(fields=["created_at"], name="idx_assess_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_order",
                    models.IntegerField(unique=True, verbose_name="题目顺序"),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("EI", "外向-内向"),
                            ("SN", "实感-直觉"),
                            ("TF", "思考-情感"),
                            ("JP", "判断-感知"),
                        ],
                        max_length=2,
                        verbose_name="所属维度",
                    ),
                ),
                ("facet", models.CharField(max_length=32, verbose_name="面向名称")),
                ("facet_order", models.IntegerField(verbose_name="面向内序号")),
                ("text_a", models.CharField(max_length=256, verbose_name="A极描述")),
                ("text_b", models.CharField(max_length=256, verbose_name="B极描述")),
                ("pole_a", models.CharField(max_length=2, verbose_name="A极字母")),
                ("pole_b", models.CharField(max_length=2, verbose_name="B极字母")),
                (
                    "is_reverse",
                    models.BooleanField(default=False, verbose_name="是否反向题"),
                ),
                ("display_order", models.IntegerField(verbose_name="展示顺序")),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "db_table": "question",
                "indexes": [
                    models.Index(fields=["dimension"], name="idx_dimension"),
                    models.Index(fields=["dimension", "facet_order"], name="idx_facet"),
                ],
            },
        ),
    ]
