# Generated by Django 5.2 on 2026-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order_id",
                    models.CharField(db_index=True, max_length=64, unique=True, verbose_name="订单号"),
                ),
                (
                    "session_token",
                    models.CharField(db_index=True, max_length=36, verbose_name="会话令牌"),
                ),
                (
                    "assessment_id",
                    models.BigIntegerField(null=True, verbose_name="关联的测评 ID"),
                ),
                (
                    "device_fingerprint",
                    models.CharField(max_length=64, verbose_name="设备指纹"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="金额"),
                ),
                (
                    "product_name",
                    models.CharField(
                        default="职业人格深度报告",
                        max_length=100,
                        verbose_name="商品名称",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("expired", "已过期"),
                            ("failed", "支付失败"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_channel",
                    models.CharField(max_length=20, null=True, verbose_name="支付渠道"),
                ),
                (
                    "transaction_id",
                    models.CharField(max_length=64, null=True, verbose_name="交易号"),
                ),
                (
                    "signature",
                    models.CharField(max_length=128, verbose_name="HMAC-SHA256 签名"),
                ),
                ("paid_at", models.DateTimeField(null=True, verbose_name="支付时间")),
                (
                    "expired_at",
                    models.DateTimeField(null=True, verbose_name="过期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "order",
                "ordering": ["-created_at"],
            },
        ),
    ]
