# Generated by Django 5.2 on 2026-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerServiceMessage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_token",
                    models.CharField(db_index=True, max_length=36, verbose_name="会话令牌"),
                ),
                (
                    "device_fingerprint",
                    models.CharField(max_length=64, verbose_name="设备指纹"),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "is_from_user",
                    models.BooleanField(default=True, verbose_name="是否用户发送"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "客服消息",
                "verbose_name_plural": "客服消息",
                "db_table": "customer_service_message",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_token",
                    models.CharField(db_index=True, max_length=36, verbose_name="会话令牌"),
                ),
                (
                    "device_fingerprint",
                    models.CharField(max_length=64, verbose_name="设备指纹"),
                ),
                ("content", models.TextField(verbose_name="反馈内容")),
                ("rating", models.IntegerField(null=True, verbose_name="评分 1-5")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "db_table": "feedback",
            },
        ),
        migrations.CreateModel(
            name="StatsDaily",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="日期"),
                ),
                ("dau", models.IntegerField(default=0, verbose_name="日活")),
                (
                    "assessment_count",
                    models.IntegerField(default=0, verbose_name="测评完成数"),
                ),
                (
                    "completion_rate",
                    models.FloatField(default=0.0, verbose_name="完成率"),
                ),
                (
                    "payment_count",
                    models.IntegerField(default=0, verbose_name="付费数"),
                ),
                (
                    "conversion_rate",
                    models.FloatField(default=0.0, verbose_name="转化率"),
                ),
                ("share_count", models.IntegerField(default=0, verbose_name="分享数")),
                ("share_rate", models.FloatField(default=0.0, verbose_name="分享率")),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="收入"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "每日统计",
                "verbose_name_plural": "每日统计",
                "db_table": "stats_daily",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_token",
                    models.CharField(db_index=True, max_length=36, verbose_name="会话令牌"),
                ),
                (
                    "device_fingerprint",
                    models.CharField(db_index=True, max_length=64, verbose_name="设备指纹"),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="page_view/start_assessment/submit_answer/generate_card/click_pay/pay_success/share/report_read",
                        max_length=30,
                        verbose_name="事件类型",
                    ),
                ),
                ("event_data", models.JSONField(default=dict, verbose_name="事件数据")),
                (
                    "page_name",
                    models.CharField(max_length=50, null=True, verbose_name="页面名称"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "埋点事件",
                "verbose_name_plural": "埋点事件",
                "db_table": "tracking_event",
                "ordering": ["-created_at"],
            },
        ),
    ]
