# Generated by Django 5.0.6 on 2026-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MBTIType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="类型代码"
                    ),
                ),
                ("type_name", models.CharField(max_length=32, verbose_name="类型名称")),
                (
                    "type_slogan",
                    models.CharField(max_length=64, verbose_name="类型标语"),
                ),
                ("role_group", models.CharField(max_length=16, verbose_name="角色组")),
                (
                    "rarity",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="稀有度百分比"
                    ),
                ),
                (
                    "rarity_label",
                    models.CharField(max_length=32, verbose_name="稀有度标签"),
                ),
                ("famous_people", models.JSONField(verbose_name="代表名人")),
                ("best_partners", models.JSONField(verbose_name="最佳搭档")),
                ("romantic_matches", models.JSONField(verbose_name="恋爱适配")),
                (
                    "mascot_url",
                    models.CharField(max_length=256, verbose_name="人偶图片URL"),
                ),
                ("type_description", models.TextField(verbose_name="类型简述")),
                ("cognitive_stack", models.JSONField(verbose_name="认知功能栈")),
                (
                    "report_personality_analysis",
                    models.TextField(verbose_name="第二章：人格特征分析"),
                ),
                ("report_strengths", models.JSONField(verbose_name="第五章：4项优势")),
                ("report_weaknesses", models.JSONField(verbose_name="第六章：4项劣势")),
                ("report_growth", models.JSONField(verbose_name="第七章：4条成长建议")),
                (
                    "report_cognitive",
                    models.JSONField(verbose_name="第八章：荣格八维解读"),
                ),
                ("report_romance", models.TextField(verbose_name="第九章：恋爱专题")),
                (
                    "report_romantic_matches",
                    models.JSONField(verbose_name="第十章：3个最佳恋爱对象"),
                ),
                ("report_career", models.JSONField(verbose_name="第十一章：职业专题")),
                (
                    "report_career_list",
                    models.JSONField(verbose_name="第十二章：按行业分类职业"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "MBTI类型",
                "verbose_name_plural": "MBTI类型",
                "db_table": "mbti_type",
            },
        ),
    ]
