# Generated by Django 5.0.6 on 2026-07-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mbti_types", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mbtitype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="mbtitype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="更新时间"
            ),
        ),
    ]
