# Generated by Django 5.2 on 2026-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalityArchetype",
            fields=[
                (
                    "archetype_id",
                    models.IntegerField(primary_key=True, serialize=False, verbose_name="原型编号"),
                ),
                (
                    "archetype_code",
                    models.CharField(max_length=20, verbose_name="维度组合码"),
                ),
                (
                    "archetype_name",
                    models.CharField(max_length=50, verbose_name="中文画像名"),
                ),
                (
                    "archetype_slogan",
                    models.CharField(max_length=200, verbose_name="一句话描述"),
                ),
                ("rarity", models.CharField(max_length=20, verbose_name="稀有度标签")),
                ("rarity_percentage", models.FloatField(verbose_name="人口占比")),
                (
                    "famous_people",
                    models.JSONField(default=list, verbose_name="同型名人列表"),
                ),
                (
                    "best_partners",
                    models.JSONField(default=list, verbose_name="最佳协作原型 ID 列表"),
                ),
                (
                    "career_directions",
                    models.JSONField(default=list, verbose_name="推荐职业方向"),
                ),
                (
                    "o_range",
                    models.CharField(
                        choices=[("high", "高"), ("low", "低")],
                        max_length=4,
                        verbose_name="开放性区间",
                    ),
                ),
                (
                    "c_range",
                    models.CharField(
                        choices=[("high", "高"), ("low", "低")],
                        max_length=4,
                        verbose_name="尽责性区间",
                    ),
                ),
                (
                    "e_range",
                    models.CharField(
                        choices=[("high", "高"), ("low", "低")],
                        max_length=4,
                        verbose_name="外向性区间",
                    ),
                ),
                (
                    "a_range",
                    models.CharField(
                        choices=[("high", "高"), ("low", "低")],
                        max_length=4,
                        verbose_name="宜人性区间",
                    ),
                ),
                (
                    "n_range",
                    models.CharField(
                        choices=[("high", "高"), ("low", "低")],
                        max_length=4,
                        verbose_name="神经质区间",
                    ),
                ),
                (
                    "mascot_url",
                    models.CharField(max_length=200, verbose_name="吉祥物图片路径"),
                ),
            ],
            options={
                "verbose_name": "人格原型",
                "verbose_name_plural": "人格原型",
                "db_table": "personality_archetype",
            },
        ),
    ]
