# Generated by Django 5.0.6 on 2026-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "career_id",
                    models.CharField(max_length=16, unique=True, verbose_name="职业ID"),
                ),
                (
                    "career_name",
                    models.CharField(max_length=64, verbose_name="职业名称"),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="职业大类"
                    ),
                ),
                ("mbti_fit", models.JSONField(verbose_name="适配MBTI类型")),
                ("mbti_ideal", models.JSONField(verbose_name="维度理想画像")),
                ("cognitive_fit", models.JSONField(verbose_name="适配认知功能")),
                (
                    "work_style",
                    models.CharField(max_length=256, verbose_name="理想工作环境"),
                ),
                ("skill_required", models.JSONField(verbose_name="核心能力要求")),
                (
                    "salary_range",
                    models.CharField(max_length=128, verbose_name="薪资参考范围"),
                ),
                (
                    "growth_prospect",
                    models.CharField(max_length=256, verbose_name="发展前景"),
                ),
                ("description", models.TextField(verbose_name="职业简介")),
                ("match_tags", models.JSONField(verbose_name="匹配关键词")),
            ],
            options={
                "verbose_name": "职业",
                "verbose_name_plural": "职业",
                "db_table": "career",
                "indexes": [models.Index(fields=["category"], name="idx_category")],
            },
        ),
    ]
