# Generated by Django 5.0.6 on 2026-07-09 13:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="订单号"
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True, max_length=36, verbose_name="用户会话ID"
                    ),
                ),
                (
                    "assessment_id",
                    models.BigIntegerField(verbose_name="关联测评记录ID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.99"),
                        max_digits=6,
                        verbose_name="支付金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("failed", "支付失败"),
                            ("expired", "已过期"),
                            ("refunded", "已退款"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[("wechat", "微信支付"), ("alipay", "支付宝")],
                        max_length=10,
                        null=True,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="第三方支付流水号",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付成功时间"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "order",
                "indexes": [
                    models.Index(fields=["uuid"], name="idx_order_uuid"),
                    models.Index(fields=["status"], name="idx_order_status"),
                    models.Index(fields=["order_no"], name="idx_order_no"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "paid")),
                fields=("assessment_id",),
                name="unique_paid_order_per_assessment",
            ),
        ),
    ]
